EXPRESSFOOD2/apiexpressfood

- src/models/Recipe.js
- src/models/utils/Ingredient-ErrorMSGs.js
- src/models/utils/Recipe-ErrorMSGs.js
- src/models/utils/constants.js
- test/recipe-model.spec.js
Implementa el Recipe Model  con validaciones de Base de Datos
> Recipe Model w/tests

- src/models/Ingredient.js
- src/models/IngredientsRecipes.js
- src/models/Recipe.js
- src/models/utils/Ingredient-ErrorMSGs.js
- src/models/utils/Recipe-ErrorMSGs.js
- src/models/utils/constants.js
- test/ingredient-model.spec.js
- test/ingredientsRecipes-model.spec.js
- test/recipe-model.spec.js
> Feature/create IngredientsRecipes model

- src/routes/index.js
- src/routes/ingredients.js
- src/routes/recipes.js
Rutas basicas de Ingredients & Recipes VACIAS
> Rutas de acceso CRUD

- index.js
- src/controllers/recipe-get-controller.js
- src/controllers/recipe-post-controller.js
- src/models/Ingredient.js
- src/models/IngredientsRecipes.js
- src/models/Recipe.js
- src/seeds/Ingredient-seed.js
- src/seeds/Recipe-layer1-seed.js
- src/seeds/index.js
Agrega multiples ingredientes y 2 recetas de muesta a la DB cada vez que se reinicia
> Adds Seeders for Ingrediends and Layer 1 Recipes

- src/models/utils/MenuItem-ErrorMSGs.js
- src/models/utils/User-ErrorMSGs.js
- test/menu-model.spec.js
- test/user-model.spec.js
> test / user - menu

- src/controllers/recipe/recipe-post_controller.js
- src/seeds/Recipe-layer1-seed.js
Crea la ruta MAGICA de create recipe con la MATH del DeMoño
> Recipe Post Controller

- src/seeds/Ingredient-seed.js
- src/seeds/Menu-seed.js
- src/seeds/Recipe-layer1-seed.js
CUIDADO!!
Escrito a ciegas sin verificacion
(Codedo en PC ajena)
> Agrega 20 MenuItem y 1 Recipe

- src/controllers/menuItem/menuItem-get_controller.js
Incluye el model ingredient de tablas relacionadas
> Ruta MenuItems Get.. devuelve tabla intermedia

- src/controllers/HashFunction/security.js
- src/controllers/user/user-get-login_controller.js
- src/controllers/user/user-post_controller.js
- src/models/utils/constants.js
la funcion generateSecret ahora acepta un (length = 8)
se reemplaza la fn de generarToken por la funcion de arriba enviando una constante de 10 por parametro
> Hacer que la funcion acepte un argumento de length

- Doc_Rutas.md
- package.json
- src/controllers/user/user-post_controller.js
- src/middleware/ingredients_middleware.js
- src/middleware/menu_middleware.js
- src/middleware/users_middleware.js
Documenta las rutas con los que llevan y traen
> Documenta todas las rutas actuales

- src/routes/login-google.js
> auth google

- Doc_Rutas.md
- src/controllers/menuItem/menuItem-get_controller.js
- src/db.js
- src/models/Tag.js
- src/models/TagsMenuItems.js
- src/models/utils/Tag-ErrorMSGs.js
- src/seeds/Menu-seed.js
- src/seeds/MenuTags-seed.js
- src/seeds/Tag-seed.js
- src/seeds/index.js
Crea Models... Seeders
Incorpora al menu Get con y sin ID la tabla intermedia
> Con seeds & Docs

- package.json
- src/routes/login-google.js
send data  auth google to fornt
> send data to fornt

- src/controllers/user/user-get-login_controller.js
Se modifico la función userLoginController para que solo si el correo y contraseña están correctos, devuelva un obj con el estado de validación y los datos del usuario
> Modificación retorno de la función  userLoginController 

- src/controllers/HashFunction/security.js
- src/middleware/ingredients_middleware.js
- src/models/Order.js
- src/models/OrdersMenu.js
- src/models/utils/Order-ErrorMSGs.js
- src/seeds/User-seed.js
- src/seeds/index.js
> Crea Model Order

- index.js
- src/app.js
- src/socket/socket-prueba.js
> implemtacion socket io

- src/routes/login-google.js
Se actualizó el componente con unas comas que le faltaban y rompian el código
> Actualizando componente Login-google

- src/controllers/HashFunction/security.js
- src/controllers/Payments/payments-controller.js
- src/controllers/order/order-post_controller.js
- src/controllers/user/user-post_controller.js
- src/middleware/payments-middleware.js
- src/models/Order.js
- src/routes/payments/payments-router.js
- src/seeds/index.js
> Genera Ordenes de compra

- src/controllers/menuItem/menuItem-get_controller.js
- src/middleware/menu_middleware.js
se modifico menuItemsGetController para que tambien enviara los ingredientes para el funcionamiento del formulario de update menu en el front  y  tambien se comento isItAnExistingMenuItemByID debido a que no estaba definida y provocaba fallo al hacer  el update menu
> Modificaciones en menu_middleware y menuItem-get_controller

- src/controllers/order/order-get_controller.js
- src/controllers/order/order-patch_controller.js
- src/middleware/order_middleware.js
- src/routes/index.js
- src/routes/orders/order-get.js
- src/routes/orders/order-patch.js
Model Order
Permite modificar el Status
y obtener Ordenes por ID que NO TENGAN status de "Unpaid" o "Finished"
> Crear rutas, mw y ctrls

- src/controllers/menuItem/menuItem-patch_controler.js
- src/controllers/order/order-patch_controller.js
- src/middleware/menu_middleware.js
if ( !(await isItAnExistingModelByID(id, store_id,MenuItem)) ) throw Error(ERROR_NOT_FOUND)
> arreglando bug

- Doc_Rutas.md
- src/controllers/HashFunction/security.js
- src/controllers/token/token_controller.js
- src/controllers/user/user-get-login_controller.js
- src/db.js
- src/middleware/menu_middleware.js
- src/middleware/users_middleware.js
- src/models/Token.js
Crea el componente login
Model,
Implementa el JWT
y prepara todo para el uso de auth y protección de rutas
> Agregar Login y tokens
